server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <client-id>
            client-secret: <secret>

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
